name: Update pre-built Python docker image
on:
  push:
    branches:
      - main

jobs:
  develop:
    name: Development Pre-built Python image
    steps:
    - name: Hit endpoint and build Python server function pre-built image from scratch
      run: |
        curl -X POST \
        https://develop-k8s.polyapi.io/functions/server/prebuilt-base-image \
        -H "Authorization: Bearer ${{ secrets.POLY_SUPER_ADMIN_USER_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"language": "python"}'