  - name: Create dummy poly directory for tests
    run: mkdir -p polyapi/poly

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r dev_requirements.txt

  - name: Run tests
    run: pytest tests/ 