name: Update pre-built Python docker image
on:
  push:
    branches:
      - main

jobs:
  update-pre-built-python-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          version:
            - pyproject.toml

    - if: steps.changes.outputs.version == 'true'
      name: trigger pre-built base image update
      run: |
        curl --fail-with-body -X POST \
        https://develop-k8s.polyapi.io/functions/server/prebuilt-base-image \
        -H "Authorization: Bearer ${{ secrets.POLY_SUPER_ADMIN_USER_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"language": "python"}'